//user login
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const PROCESS_LOGOUT = 'PROCESS_LOGOUT';

// manage crud
export const GET_USERS = 'GET_USERS';
export const DELETE_USER = 'DELETE_USER';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_SINGLE_USER = 'GET_SINGLE_USER';

// genders
export const FETCH_GENDER_START = 'FETCH_GENDER_START';
export const FETCH_GENDER_SUCCESS = 'FETCH_GENDER_SUCCESS';
export const FETCH_GENDER_FAILED = 'FETCH_GENDER_FAILED';

// schedule teacher
export const FETCH_ALL_DOCTORS_SUCCESS = 'FETCH_ALL_DOCTORS_SUCCESS';
export const FETCH_ALL_DOCTORS_FAILED = 'FETCH_ALL_DOCTORS_FAILED';

// schedule teacher time
export const FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS = 'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS';
export const FETCH_ALLCODE_SCHEDULE_TIME_FAILED = 'FETCH_ALLCODE_SCHEDULE_TIME_FAILED';

// teacher info
export const FETCH_REQUIRED_DOCTOR_INFOR_START = 'FETCH_REQUIRED_DOCTOR_INFOR_START';
export const FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS = 'FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS';
export const FETCH_REQUIRED_DOCTOR_INFOR_FAILED = 'FETCH_REQUIRED_DOCTOR_INFOR_FAILED';

// save detail info teacher
export const SAVE_DETAIL_DOCTOR_SUCCESS = 'SAVE_DETAIL_DOCTOR_SUCCESS';
export const SAVE_DETAIL_DOCTOR_FAILED = 'SAVE_DETAIL_DOCTOR_FAILED';

// crud redux manage
export const FETCH_POSITION_SUCCESS = 'FETCH_POSITION_SUCCESS';
export const FETCH_POSITION_FAILED = 'FETCH_POSITION_FAILED';

export const FETCH_ROLE_SUCCESS = 'FETCH_ROLE_SUCCESS';
export const FETCH_ROLE_FAILED = 'FETCH_ROLE_FAILED';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_FAILED = 'FETCH_ALL_USERS_FAILED';
